//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSMC.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSMC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ---------------------------------------------------------
        ///---------      CUSTOM MODEL PATTERN     ------------
        ///---------------------------------------------------------
        ///
        ///
        ///ITEM.Name = &apos;%MODEL_NAME%&apos;
        ///ITEM.Price = %MODEL_PRICE%
        ///ITEM.Model = &apos;%MODEL_VIRTUAL_PATH%&apos;
        ///
        ///
        ///function ITEM:OnEquip(ply)
        ///	ply:PS_AddClientsideModel(self.ID)
        ///end
        ///
        ///function ITEM:OnHolster(ply)
        ///	ply:PS_RemoveClientsideModel(self.ID)
        ///end
        ///
        ///function ITEM:ModifyClientsideModel(ply, model, pos, ang)
        ///	return model, pos, ang
        ///end ähnelt.
        /// </summary>
        internal static string CustomModelPatternBackup {
            get {
                return ResourceManager.GetString("CustomModelPatternBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -----------------------------------------------------------
        ///---------      CUSTOM MODEL PATTERN     --------------
        ///-----------------------------------------------------------
        ///
        ///
        ///ITEM.Name = &apos;%MODEL_NAME%&apos;
        ///ITEM.Price = %MODEL_PRICE%
        ///ITEM.Model = &apos;%MODEL_VIRTUAL_PATH%&apos;
        ///
        ///
        ///function ITEM:OnEquip(ply)
        ///	ply:PS_AddClientsideModel(self.ID)
        ///end
        ///
        ///function ITEM:OnHolster(ply)
        ///	ply:PS_RemoveClientsideModel(self.ID)
        ///end
        ///
        ///function ITEM:ModifyClientsideModel(ply, model, pos, ang)
        ///	return model, pos, ang
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string HatModelPattern {
            get {
                return ResourceManager.GetString("HatModelPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ITEM.Name = &apos;%MODEL_NAME%&apos;
        ///ITEM.Price = %MODEL_PRICE%
        ///ITEM.Model = &apos;%MODEL_VIRTUAL_PATH%&apos;
        ///ITEM.Bone = &apos;ValveBiped.Bip01_Spine2&apos;
        ///
        ///function ITEM:OnEquip(ply, modifications)
        ///	ply:PS_AddClientsideModel(self.ID)
        ///end
        ///
        ///function ITEM:OnHolster(ply)
        ///	ply:PS_RemoveClientsideModel(self.ID)
        ///end ähnelt.
        /// </summary>
        internal static string ItemModelPattern {
            get {
                return ResourceManager.GetString("ItemModelPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ITEM.Name = &apos;%MODEL_NAME%&apos;
        ///ITEM.Price = %MODEL_PRICE%
        ///ITEM.Model = &apos;%MODEL_VIRTUAL_PATH%&apos;
        ///
        ///function ITEM:OnEquip(ply, modifications)
        ///	if not ply._OldModel then
        ///		ply._OldModel = ply:GetModel()
        ///	end
        ///	
        ///	timer.Simple(1, function() ply:SetModel(self.Model) end)
        ///end
        ///
        ///function ITEM:OnHolster(ply)
        ///	if ply._OldModel then
        ///		ply:SetModel(ply._OldModel)
        ///	end
        ///end
        ///
        ///function ITEM:PlayerSetModel(ply)
        ///	ply:SetModel(self.Model)
        ///end
        ///
        ///if (SERVER) then
        ///	player_manager.AddValidModel( &quot;%MODEL_CLEAN_NAME%&quot;, [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PlayerModelPattern {
            get {
                return ResourceManager.GetString("PlayerModelPattern", resourceCulture);
            }
        }
    }
}
